name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ${{matrix.os}}
    # continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.13"]
        # python: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.3"
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Sync uv
      run: uv sync

    - name: Test shedskin
      run: |
        cd tests
        uv run shedskin test --conan

    - name: Test shedskin examples
      run: |
        cd examples
        uv run shedskin test --conan
